import { DatabaseState, Role } from './types';
import { buildEnvAdminUser, getEnvAdminCredentials } from './utils/adminAuth';

export function createDefaultState(): DatabaseState {
  const creds = getEnvAdminCredentials();
  const adminEmail = creds.email;
  const adminPassword = creds.password;
  const adminName = creds.name;

  return {
    users: [
      {
        email: adminEmail,
        role: Role.ADMIN,
        invitedAt: new Date().toISOString(),
        passcode: '0000',
        fullName: adminName,
        username: 'superadmin',
        password: adminPassword,
        mobile: '',
        status: 'active',
        isSuperAdmin: true,
      },
    ],
    rolePermissions: {
      [Role.ADMIN]: { orderProcess: true, accounts: true, productEdit: true, purchaseEntry: true, systemSettings: true },
      [Role.MANAGER]: { orderProcess: true, accounts: false, productEdit: true, purchaseEntry: true, systemSettings: false },
      [Role.STAFF]: { orderProcess: true, accounts: false, productEdit: false, purchaseEntry: false, systemSettings: false },
    },
    staffRoleCategories: [
      { id: Role.ADMIN, roleKey: Role.ADMIN, name: 'Admin', description: 'Full system access.', createdAt: new Date().toISOString() },
      { id: Role.MANAGER, roleKey: Role.MANAGER, name: 'Manager', description: 'Catalog and order management access.', createdAt: new Date().toISOString() },
      { id: Role.STAFF, roleKey: Role.STAFF, name: 'Staff', description: 'Order operations access.', createdAt: new Date().toISOString() },
    ],
    categories: [],
    brands: [],
    products: [],
    inventoryLogs: [],
    reviews: [],
    coupons: [],
    leads: [],
    orders: [],
    currencies: [{ code: 'NPR', symbol: 'Rs.', rateToNPR: 1.0, isDefault: true }],
    plugins: {
      whatsappNumber: '',
      whatsappMessage: 'Hi, I need help with my order.',
      googleAnalyticsId: '',
      facebookPixelId: '',
      whatsappIconType: 'whatsapp',
      whatsappCustomSvg: '',
    },
    appearance: {
      themeMode: 'light',
      primaryColor: '#E91E63',
      secondaryColor: '#C2185B',
      siteLogo: '',
      navbarLinks: [],
      domainName: '',
      favImage: '',
      slogan: 'मायाको कोसेली',
      stickyNotice: 'Same-Day Flowers & Cake Delivery Available in all major cities in Nepal — Order by 4:00 PM NST',
      websiteTextFont: 'poppins',
      shippingNotice: '',
      shortTermsAndConditions: '',
      fullTermsAndConditions: '',
      giftingSlaDisclaimer: '',
      brandDescriptionStyle: 'Nepal\'s premium gifting destination — handcrafted hampers, fresh flowers, and gourmet treats delivered with elegance across Kathmandu and beyond.',
      secureLogisticsTitle: '',
      secureLogisticsDesc: '',
      craftGuaranteeDesc: '',
      footerAboutLinks: [],
      footerCategoriesLinks: [],
      footerLegalsLinks: [],
      footerSocialsLinks: [],
      registeredBusinessName: '',
      panVatNumber: '',
      companyAddress: '',
      registrationNumber: '',
      contactEmail: '',
      ecommerceNumber: '',
      outlets: '',
      complainOfficerName: '',
      complainOfficerPhone: '',
      complainOfficerEmail: '',
      categoryDiscounts: [],
      paymentDiscounts: [],
    },
    store: {
      storeName: 'Koseli Xpress',
      supportEmail: '',
      supportPhone: '',
      address: '',
      baseCurrencyCode: 'NPR',
      orderPrefix: 'KO-',
      maintenanceMode: false,
      geoRegion: 'NP-BA',
      geoPlacename: 'Kathmandu, Nepal',
      geoPosition: '27.717244;85.324060',
    },
    serviceFees: [],
    pages: [],
    deliveryDistricts: [
      { id: 'dist-kathmandu', name: 'Kathmandu', chargeNPR: 150 },
      { id: 'dist-lalitpur', name: 'Lalitpur', chargeNPR: 150 },
      { id: 'dist-bhaktapur', name: 'Bhaktapur', chargeNPR: 200 },
      { id: 'dist-pokhara', name: 'Pokhara', chargeNPR: 350 },
      { id: 'dist-chitwan', name: 'Chitwan', chargeNPR: 400 },
      { id: 'dist-other', name: 'Other / Outside Valley', chargeNPR: 500 },
    ],
    deliveryGroups: [],
    paymentGateways: [
      {
        id: 'esewa',
        name: 'eSewa Wallet Payment',
        logoUrl: 'https://esewa.com.np/common/images/esewa_logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 2,
        mappedAccountId: '',
      },
      {
        id: 'khalti',
        name: 'Khalti Mobile Wallet',
        logoUrl: 'https://blog.khalti.com/wp-content/uploads/2021/01/khalti-logo.png',
        merchantId: '',
        secretKey: '',
        publicKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 3,
        mappedAccountId: '',
      },
      {
        id: 'fonepay_static',
        name: 'Fonepay Static QR',
        logoUrl: 'https://brandessentials.org/wp-content/uploads/2023/12/fonepay-logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 4,
        mappedAccountId: '',
        extraSettings: { fonepayUsername: '', fonepayPassword: '', qrImageUrl: '' },
      },
      {
        id: 'fonepay_dynamic',
        name: 'Fonepay Dynamic QR',
        logoUrl: 'https://brandessentials.org/wp-content/uploads/2023/12/fonepay-logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 5,
        mappedAccountId: '',
        extraSettings: { fonepayUsername: '', fonepayPassword: '' },
      },
      { id: 'nps', name: 'Visa Card & Master Card', merchantId: '', secretKey: '', apiEnvironment: 'test', isEnabled: false, priority: 5, mappedAccountId: '', extraSettings: { merchantName: '', apiUsername: '', apiPassword: '' } },
      { id: 'manual', name: 'Manual Bank Transfer / QR Pay', merchantId: 'MANUAL', secretKey: '', apiEnvironment: 'test', isEnabled: false, priority: 6, mappedAccountId: '', extraSettings: { bankName: '', accountName: '', accountNumber: '', branchName: '', instructions: '', qrImageUrl: '' } },
      { id: 'cod', name: 'Cash on Delivery (COD)', logoUrl: '', merchantId: 'COD', secretKey: '', apiEnvironment: 'live', isEnabled: false, priority: 1, mappedAccountId: '', extraSettings: { instructions: 'Pay the delivery rider in cash when your gift arrives.' } },
    ],
    vendors: [],
    purchaseEntries: [],
    expenseEntries: [],
    treasuryAccounts: [],
    treasuryTransactions: [],
    complianceFooter: {
      registeredBusinessName: '',
      registrationNumber: '',
      panVatNumber: '',
      ecommerceNumber: '',
      establishmentDate: '',
      regulatoryAuthority: '',
      licenseNumber: '',
      certificationInfo: '',
      supportEmail: '',
      supportPhone: '',
      corporateEmail: '',
      corporatePhone: '',
      registeredOfficeAddress: '',
      headOfficeAddress: '',
      outlets: '',
      complianceOfficerName: '',
      complianceOfficerMobile: '',
      complianceOfficerEmail: '',
      additionalComplianceDetails: '',
      popularCategoriesEnabled: true,
      footerGroups: [
        {
          id: 'group-about',
          title: 'Company',
          links: [
            { id: 'l-about', label: 'About Us', url: '/page/about' },
            { id: 'l-contact', label: 'Contact', url: '/page/contact' },
            { id: 'l-offers', label: 'Offers', url: '/page/offers' },
            { id: 'l-blog', label: 'Blog & Guides', url: '/blog' },
          ],
        },
        {
          id: 'group-legal',
          title: 'Policies',
          links: [
            { id: 'l-ship', label: 'Shipping Policy', url: '/page/shipping-policy' },
            { id: 'l-refund', label: 'Refund Policy', url: '/page/refund-policy' },
            { id: 'l-privacy', label: 'Privacy Policy', url: '/page/privacy-policy' },
            { id: 'l-terms', label: 'Terms of Service', url: '/page/terms-of-service' },
          ],
        },
      ],
      socials: [
        { id: 'soc-fb', platform: 'facebook', url: 'https://facebook.com', isEnabled: true },
        { id: 'soc-ig', platform: 'instagram', url: 'https://instagram.com', isEnabled: true },
        { id: 'soc-tt', platform: 'tiktok', url: 'https://tiktok.com', isEnabled: true },
      ],
    },
    smtpSettings: {
      isEnabled: false,
      gmailAddress: '',
      appPassword: '',
      senderName: 'Koseli Xpress',
      replyToEmail: '',
    },
    emailTemplates: [
      { id: 'confirmation', name: 'Order Confirmation Email', subject: 'Order Confirmed - #{{orderNumber}}', body: '<p>Your order #{{orderNumber}} has been received.</p>' },
      { id: 'processing', name: 'Order Processing Email', subject: 'Order #{{orderNumber}} is being prepared', body: '<p>Your order is being prepared.</p>' },
      { id: 'shipped', name: 'Order Shipped', subject: 'Order #{{orderNumber}} is on the way', body: '<p>Your order is out for delivery.</p>' },
      { id: 'delivered', name: 'Order Delivered', subject: 'Order #{{orderNumber}} delivered', body: '<p>Your order has been delivered.</p>' },
      { id: 'cancelled', name: 'Order Cancelled', subject: 'Order #{{orderNumber}} cancelled', body: '<p>Your order has been cancelled.</p>' },
    ],
    emailLogs: [],
    visitorTracks: [],
    customerAuthConfig: {
      enableGoogleLogin: true,
      enableGuestCheckout: true,
      enableAutoOrderLinking: true,
      googleClientId: '',
      googleClientSecret: '',
      googleRedirectUrl: '',
      auth0Domain: '',
      auth0ClientId: '',
      matchOrdersByEmail: true,
      enableAutoMerge: true,
      enableAccountCreationOnLogin: true,
      allowDuplicateEmails: false,
      sessionTimeoutMinutes: 60,
    },
    supportChats: [],
    specialDayReminders: [],
  };
}
