import { DatabaseState, Role } from './types';
import { buildEnvAdminUser, getEnvAdminCredentials } from './utils/adminAuth';

export function createDefaultState(): DatabaseState {
  const creds = getEnvAdminCredentials();
  const adminEmail = creds.email;
  const adminPassword = creds.password;
  const adminName = creds.name;

  return {
    users: [
      {
        email: adminEmail,
        role: Role.ADMIN,
        invitedAt: new Date().toISOString(),
        passcode: '0000',
        fullName: adminName,
        username: 'superadmin',
        password: adminPassword,
        mobile: '',
        status: 'active',
        isSuperAdmin: true,
      },
    ],
    rolePermissions: {
      [Role.ADMIN]: { orderProcess: true, accounts: true, productEdit: true, purchaseEntry: true, systemSettings: true },
      [Role.MANAGER]: { orderProcess: true, accounts: false, productEdit: true, purchaseEntry: true, systemSettings: false },
      [Role.STAFF]: { orderProcess: true, accounts: false, productEdit: false, purchaseEntry: false, systemSettings: false },
    },
    categories: [],
    brands: [],
    products: [],
    inventoryLogs: [],
    reviews: [],
    coupons: [],
    leads: [],
    orders: [],
    currencies: [{ code: 'NPR', symbol: 'Rs.', rateToNPR: 1.0, isDefault: true }],
    plugins: {
      whatsappNumber: '',
      whatsappMessage: 'Hi, I need help with my order.',
      googleAnalyticsId: '',
      facebookPixelId: '',
      whatsappIconType: 'whatsapp',
      whatsappCustomSvg: '',
    },
    appearance: {
      themeMode: 'light',
      primaryColor: '#E91E63',
      secondaryColor: '#C2185B',
      siteLogo: '',
      navbarLinks: [],
      domainName: '',
      favImage: '',
      slogan: 'मायाको कोसेली',
      stickyNotice: 'Same-Day Flowers & Cake Delivery Available in all major cities in Nepal — Order by 4:00 PM NST',
      websiteTextFont: 'poppins',
      shippingNotice: '',
      shortTermsAndConditions: '',
      fullTermsAndConditions: '',
      giftingSlaDisclaimer: '',
      brandDescriptionStyle: 'Nepal\'s premium gifting destination — handcrafted hampers, fresh flowers, and gourmet treats delivered with elegance across Kathmandu and beyond.',
      secureLogisticsTitle: '',
      secureLogisticsDesc: '',
      craftGuaranteeDesc: '',
      footerAboutLinks: [],
      footerCategoriesLinks: [],
      footerLegalsLinks: [],
      footerSocialsLinks: [],
      registeredBusinessName: '',
      panVatNumber: '',
      companyAddress: '',
      registrationNumber: '',
      contactEmail: '',
      ecommerceNumber: '',
      outlets: '',
      complainOfficerName: '',
      complainOfficerPhone: '',
      complainOfficerEmail: '',
      categoryDiscounts: [],
      paymentDiscounts: [],
    },
    store: {
      storeName: 'Koseli Xpress',
      supportEmail: '',
      supportPhone: '',
      address: '',
      baseCurrencyCode: 'NPR',
      orderPrefix: 'KO-',
      maintenanceMode: false,
      geoRegion: 'NP-BA',
      geoPlacename: 'Kathmandu, Nepal',
      geoPosition: '27.717244;85.324060',
    },
    serviceFees: [],
    pages: [
      {
        id: 'page-home',
        title: 'Home Page',
        slug: 'home',
        status: 'active',
        metaTitle: 'Koseli Xpress',
        metaDescription: 'Premium gifting platform in Nepal',
        metaKeywords: 'gifts, nepal, koseli xpress',
        sections: [
          {
            id: 'sec-banner',
            type: 'banner',
            data: {
              scriptTitle: 'Celebrate',
              boldSubtitle: 'SAME DAY DELIVERY',
              title: 'Premium flowers & gifts across Nepal',
              subtitle: 'Fresh bouquets, gourmet cakes, and curated hampers — hand-delivered with love.',
              buttonText: 'ORDER NOW',
              buttonUrl: '#shop-collection',
              imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop',
              heroNavLinks: ['FLOWER DELIVERY', 'ALL GIFT ITEMS', 'FRESH FLOWER', 'CAKES'],
              pillTags: ['All Over Nepal', 'Fresh Flowers | Long Life Flowers'],
            },
          },
          {
            id: 'sec-trust',
            type: 'trust_strip',
            data: {
              items: [
                { icon: 'truck', title: 'Express Delivery', desc: 'Same-day dispatch in Kathmandu Valley' },
                { icon: 'gift', title: 'Artisan Wrapped', desc: 'Every gift hand-prepared with care' },
                { icon: 'shield', title: 'Secure Payments', desc: 'eSewa, Khalti, cards & more' },
                { icon: 'heart', title: 'Made with Love', desc: 'Premium quality, every time' },
              ],
            },
          },
          {
            id: 'sec-cats',
            type: 'categories_grid',
            data: { title: 'Shop by Category', subtitle: 'Curated Collections' },
          },
          {
            id: 'sec-products',
            type: 'products_grid',
            data: { title: 'Featured Gifts', subtitle: 'Handpicked for You', productIds: [] },
          },
          {
            id: 'sec-story',
            type: 'image_content',
            data: {
              sectionId: 'about-story',
              title: 'Crafted with Intention, Delivered with Care',
              subtitle: 'At Koseli Xpress, every bouquet is styled by expert florists and every hamper is assembled by hand — because the people you love deserve nothing less than extraordinary.',
              content: 'From Kathmandu to cities across Nepal, we bridge distances with premium gifting experiences that feel personal, polished, and unforgettable.',
              imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=800&auto=format&fit=crop',
              buttonLabel: 'Learn More',
              buttonPath: '/page/about',
              layoutPreset: 'left',
            },
          },
          {
            id: 'sec-features',
            type: 'features',
            data: {
              title: 'The Koseli Difference',
              subtitle: 'Why Choose Us',
              items: [
                { emoji: '🌸', title: 'Farm-Fresh Quality', desc: 'Flowers picked daily, cakes baked to order, chocolates sourced from premium suppliers.' },
                { emoji: '🎁', title: 'Bespoke Presentation', desc: 'Luxury wrapping, personalized cards, and elegant packaging for every occasion.' },
                { emoji: '🚀', title: 'Reliable Delivery', desc: 'Real-time tracking, preferred time slots, and dedicated support until delivery.' },
              ],
            },
          },
          {
            id: 'sec-faq',
            type: 'faq',
            data: {
              title: 'Questions & Answers',
              faqs: [
                { question: 'How fast is delivery within Kathmandu?', answer: 'Most orders within the Kathmandu Valley are delivered within 3–4 hours of confirmation. Same-day delivery is available for orders placed before 1:00 PM.' },
                { question: 'Can I send gifts from abroad?', answer: 'Yes! We accept international cards (Visa, MasterCard, Amex) and local wallets. Pay from anywhere in the world and we deliver across Nepal.' },
                { question: 'Do you offer custom hampers?', answer: 'Absolutely. Combine flowers, cakes, chocolates, and more into a personalized hamper. Contact our team for bespoke arrangements.' },
              ],
            },
          },
          {
            id: 'sec-cta',
            type: 'cta_band',
            data: {
              title: 'Ready to Make Someone\'s Day?',
              subtitle: 'Browse our collection or reach out — we\'ll help you find the perfect gift.',
              buttonText: 'Start Shopping',
              buttonUrl: '#shop-collection',
            },
          },
        ],
      },
    ],
    deliveryDistricts: [
      { id: 'dist-kathmandu', name: 'Kathmandu', chargeNPR: 150 },
      { id: 'dist-lalitpur', name: 'Lalitpur', chargeNPR: 150 },
      { id: 'dist-bhaktapur', name: 'Bhaktapur', chargeNPR: 200 },
      { id: 'dist-pokhara', name: 'Pokhara', chargeNPR: 350 },
      { id: 'dist-chitwan', name: 'Chitwan', chargeNPR: 400 },
      { id: 'dist-other', name: 'Other / Outside Valley', chargeNPR: 500 },
    ],
    deliveryGroups: [],
    paymentGateways: [
      {
        id: 'esewa',
        name: 'eSewa Wallet Payment',
        logoUrl: 'https://esewa.com.np/common/images/esewa_logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 2,
        mappedAccountId: '',
      },
      {
        id: 'khalti',
        name: 'Khalti Mobile Wallet',
        logoUrl: 'https://blog.khalti.com/wp-content/uploads/2021/01/khalti-logo.png',
        merchantId: '',
        secretKey: '',
        publicKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 3,
        mappedAccountId: '',
      },
      {
        id: 'fonepay_static',
        name: 'Fonepay Static QR',
        logoUrl: 'https://brandessentials.org/wp-content/uploads/2023/12/fonepay-logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 4,
        mappedAccountId: '',
        extraSettings: { fonepayUsername: '', fonepayPassword: '', qrImageUrl: '' },
      },
      {
        id: 'fonepay_dynamic',
        name: 'Fonepay Dynamic QR',
        logoUrl: 'https://brandessentials.org/wp-content/uploads/2023/12/fonepay-logo.png',
        merchantId: '',
        secretKey: '',
        apiEnvironment: 'test',
        isEnabled: false,
        priority: 5,
        mappedAccountId: '',
        extraSettings: { fonepayUsername: '', fonepayPassword: '' },
      },
      { id: 'nps', name: 'Visa Card & Master Card', merchantId: '', secretKey: '', apiEnvironment: 'test', isEnabled: false, mappedAccountId: '', extraSettings: { merchantName: '', apiUsername: '', apiPassword: '' } },
      { id: 'manual', name: 'Manual Bank Transfer / QR Pay', merchantId: 'MANUAL', secretKey: '', apiEnvironment: 'test', isEnabled: false, priority: 6, mappedAccountId: '', extraSettings: { bankName: '', accountName: '', accountNumber: '', branchName: '', instructions: '', qrImageUrl: '' } },
      { id: 'cod', name: 'Cash on Delivery (COD)', logoUrl: '', merchantId: 'COD', secretKey: '', apiEnvironment: 'live', isEnabled: false, priority: 1, mappedAccountId: '', extraSettings: { instructions: 'Pay the delivery rider in cash when your gift arrives.' } },
    ],
    vendors: [],
    purchaseEntries: [],
    expenseEntries: [],
    treasuryAccounts: [],
    treasuryTransactions: [],
    complianceFooter: {
      registeredBusinessName: '',
      registrationNumber: '',
      panVatNumber: '',
      ecommerceNumber: '',
      establishmentDate: '',
      regulatoryAuthority: '',
      licenseNumber: '',
      certificationInfo: '',
      supportEmail: '',
      supportPhone: '',
      corporateEmail: '',
      corporatePhone: '',
      registeredOfficeAddress: '',
      headOfficeAddress: '',
      outlets: '',
      complianceOfficerName: '',
      complianceOfficerMobile: '',
      complianceOfficerEmail: '',
      additionalComplianceDetails: '',
      popularCategoriesEnabled: true,
      footerGroups: [
        {
          id: 'group-about',
          title: 'Company',
          links: [
            { id: 'l-about', label: 'About Us', url: '/page/about' },
            { id: 'l-contact', label: 'Contact', url: '/page/contact' },
            { id: 'l-offers', label: 'Offers', url: '/page/offers' },
            { id: 'l-blog', label: 'Blog & Guides', url: '/blog' },
          ],
        },
        {
          id: 'group-legal',
          title: 'Policies',
          links: [
            { id: 'l-ship', label: 'Shipping Policy', url: '/page/shipping-policy' },
            { id: 'l-refund', label: 'Refund Policy', url: '/page/refund-policy' },
            { id: 'l-privacy', label: 'Privacy Policy', url: '/page/privacy-policy' },
            { id: 'l-terms', label: 'Terms of Service', url: '/page/terms-of-service' },
          ],
        },
      ],
      socials: [
        { id: 'soc-fb', platform: 'facebook', url: 'https://facebook.com', isEnabled: true },
        { id: 'soc-ig', platform: 'instagram', url: 'https://instagram.com', isEnabled: true },
        { id: 'soc-tt', platform: 'tiktok', url: 'https://tiktok.com', isEnabled: true },
      ],
    },
    smtpSettings: {
      isEnabled: false,
      gmailAddress: '',
      appPassword: '',
      senderName: 'Koseli Xpress',
      replyToEmail: '',
    },
    emailTemplates: [
      { id: 'confirmation', name: 'Order Confirmation Email', subject: 'Order Confirmed - #{{orderNumber}}', body: '<p>Your order #{{orderNumber}} has been received.</p>' },
      { id: 'processing', name: 'Order Processing Email', subject: 'Order #{{orderNumber}} is being prepared', body: '<p>Your order is being prepared.</p>' },
      { id: 'shipped', name: 'Order Shipped', subject: 'Order #{{orderNumber}} is on the way', body: '<p>Your order is out for delivery.</p>' },
      { id: 'delivered', name: 'Order Delivered', subject: 'Order #{{orderNumber}} delivered', body: '<p>Your order has been delivered.</p>' },
      { id: 'cancelled', name: 'Order Cancelled', subject: 'Order #{{orderNumber}} cancelled', body: '<p>Your order has been cancelled.</p>' },
    ],
    emailLogs: [],
    visitorTracks: [],
    customerAuthConfig: {
      enableGoogleLogin: true,
      enableGuestCheckout: true,
      enableAutoOrderLinking: true,
      googleClientId: '',
      googleClientSecret: '',
      googleRedirectUrl: '',
      auth0Domain: '',
      auth0ClientId: '',
      matchOrdersByEmail: true,
      enableAutoMerge: true,
      enableAccountCreationOnLogin: true,
      allowDuplicateEmails: false,
      sessionTimeoutMinutes: 60,
    },
    supportChats: [],
    specialDayReminders: [],
  };
}
